sudo: false
language: node_js
node_js: '4'
cache:
  directories: node_modules
before_script: npm prune
branches:
  except: /^v\d+\.\d+\.\d+$/
notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change
    on_failure: always
    on_start: false
  email: false
script: npm run test-ci
addons:
  sauce_connect: true
env:
  global:
  - secure: nwI6HTDLmu5YnsQP0MaxC9Vu6LCHHpeZAWlinMVRQ2i9qDRgIZiiP1kO6KGkx/V1tilA+y3+mP4dXeabWOg/+49QLOhzyRktDlFOEfB5qrfniAwdhJTOT3U6LsTez6xR48EbNFqZggiWfZwVzmnMrEYMA7zUdPTuzAri8QH+CWw=
  - secure: SkmqFwIEjUrpt+A6p2TWhagfNZ9e/q5X9403mrz6VW8AOr7nTkiZgzSeP+dFmbX2uSUvX39Hdn/FFp0VNfs6comlgrjCibPCRbhhIO6nE99xTPS6+fh6mbEgbCYoLU33wRQf9d64nWnnDSAMc41fGct2ZcmkCQ3zFpS/yJqyMMc=
